// const promise = new Promise((resolve, reject) => {
//   setTimeout(() => {
//     // can only resolve a single time. can only pass in 1 argument
//     reject('sum ting wong');
//   }, 5000);
// });

// console.log('before')

// promise.then((data) => {
//   console.log('1', data);
// }).catch((error) => {
//   console.log('error: ', error)
// });

// console.log('after')
